# Generated by Django 5.2 on 2025-05-13 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specialite', '0002_cours'),
        ('stagiaire', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stagiaire',
            name='specialite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='specialite.specialite'),
        ),
    ]
