# Generated by Django 5.2 on 2025-05-13 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stagiaire', '0002_alter_stagiaire_specialite'),
    ]

    operations = [
        migrations.AddField(
            model_name='stagiaire',
            name='adresse',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stagiaire',
            name='nom',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stagiaire',
            name='prenom',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='stagiaire',
            name='tel',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
