# Generated by Django 5.2.1 on 2025-05-19 09:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specialite', '0002_cours'),
        ('stagiaire', '0003_stagiaire_adresse_stagiaire_nom_stagiaire_prenom_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stagiaire',
            options={'verbose_name': 'Stagiaire', 'verbose_name_plural': 'Stagiaires'},
        ),
        migrations.RemoveField(
            model_name='stagiaire',
            name='date_inscription',
        ),
        migrations.RemoveField(
            model_name='stagiaire',
            name='nom',
        ),
        migrations.RemoveField(
            model_name='stagiaire',
            name='prenom',
        ),
        migrations.RemoveField(
            model_name='stagiaire',
            name='specialite',
        ),
        migrations.RemoveField(
            model_name='stagiaire',
            name='tel',
        ),
        migrations.AddField(
            model_name='stagiaire',
            name='date_naissance',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stagiaire',
            name='specialites',
            field=models.ManyToManyField(related_name='stagiaires', to='specialite.specialite'),
        ),
        migrations.AddField(
            model_name='stagiaire',
            name='statut',
            field=models.CharField(choices=[('ACTIF', 'Actif'), ('EN_PAUSE', 'En pause'), ('DIPLOME', 'Diplômé'), ('ABANDON', 'Abandon'), ('INSCRIT', 'Inscrit (en attente de début)')], default='INSCRIT', max_length=20),
        ),
        migrations.AlterField(
            model_name='stagiaire',
            name='adresse',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stagiaire',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stagiaire_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
