# Generated by Django 5.2.1 on 2025-05-19 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stagiaire', '0004_alter_stagiaire_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stagiaire',
            name='nom',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stagiaire',
            name='prenom',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='stagiaire',
            name='adresse',
            field=models.TextField(),
        ),
    ]
