# Generated by Django 5.2.1 on 2025-05-19 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stagiaire', '0005_stagiaire_nom_stagiaire_prenom_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stagiaire',
            name='nom',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
