# Generated by Django 5.2.1 on 2025-05-19 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('formateur', '0003_remove_formateur_tel'),
        ('specialite', '0002_cours'),
        ('stagiaire', '0006_alter_stagiaire_nom'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text='Nom ou titre de la session (ex: Session Printemps 2025)', max_length=255)),
                ('date_debut', models.DateField(help_text='Date de début de la session')),
                ('date_fin', models.DateField(help_text='Date de fin de la session')),
                ('statut', models.CharField(choices=[('OUVERTE', 'Ouverte'), ('EN_COURS', 'En cours'), ('TERMINEE', 'Terminée'), ('FERMEE', 'Fermée')], default='OUVERTE', help_text='Statut actuel de la session', max_length=20)),
                ('lieu', models.CharField(blank=True, help_text='Lieu où se déroule la session', max_length=255, null=True)),
                ('capacite_maximale', models.IntegerField(blank=True, help_text='Nombre maximal de stagiaires pour cette session', null=True)),
                ('formateurs', models.ManyToManyField(help_text='Formateurs assignés à cette session', related_name='sessions', to='formateur.formateur')),
                ('specialites', models.ManyToManyField(help_text='Spécialités couvertes par cette session', related_name='sessions', to='specialite.specialite')),
                ('stagiaires', models.ManyToManyField(help_text='Stagiaires inscrits à cette session', related_name='sessions', to='stagiaire.stagiaire')),
            ],
            options={
                'verbose_name': 'Session',
                'verbose_name_plural': 'Sessions',
                'ordering': ['date_debut', 'nom'],
                'constraints': [models.CheckConstraint(condition=models.Q(('date_fin__gte', models.F('date_debut'))), name='date_fin_gte_date_debut')],
            },
        ),
    ]
