# Generated by Django 5.2.1 on 2025-05-15 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formateur', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='formateur',
            name='adresse',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formateur',
            name='nom',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formateur',
            name='prenom',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='formateur',
            name='tel',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
