# Generated by Django 5.2.1 on 2025-05-19 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formateur', '0002_formateur_adresse_formateur_nom_formateur_prenom_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formateur',
            name='tel',
        ),
    ]
