# Generated by Django 5.2 on 2025-04-30 15:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specialite', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('formateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cours_donnes', to=settings.AUTH_USER_MODEL)),
                ('specialite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cours', to='specialite.specialite')),
                ('stagiaires', models.ManyToManyField(blank=True, related_name='cours_suivis', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
